---
root: true
env:
  node: true
  browser: true
extends:
  - "@chookslint/typescript/strict"
  - "@chookslint/typescript/types"
parserOptions:
  project: "./tsconfig.json"
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: "_"
